print("Mayank - 2203855")
radius = float(input("Enter the radius of sphere:"))
print("The radius of sphere is:",radius)
print("The diameter of sphere is:", 2*radius)
print("The circumference of sphere is:", 2*3.14*radius)
print("The surfaceArea of sphere is:", 4*3.14*(radius**2))
print("The volume of sphere is:", 4/3*(3.14)*(radius**3))